### ISSUE TITLE
Could you released the "scannetv2_official_split.npz"?

### ISSUE THREAD

**Issue by liujiaheng** [jchibane/Box2Mask#3]

**Comment by liujiaheng** [comment]
How about the training time for scannet?

**Comment by jchibane** [comment]
Hi Jiaheng,

**thanks for reaching out and letting us know!**
In your separate email, you mentioned two problems:  (1) Could you provide the "scannetv2_official_split.npz"?. (2) Could you provide which configuration in "configs" is used in your released model?

We are working on both problems and will follow up with an update on the code base the following days.

Best,

Julian

**Comment by jchibane** [comment]
Should be fixed now. Let me know in case there is something else. Thanks!
